event-reporter/app/blueprints/event.py
from flask import Blueprint, render_template

from app.extensions import MongoDatabase

blueprint = Blueprint("event", __name__, url_prefix='/event')


@blueprint.route("/", methods=['get'])
def show_events():
    events = MongoDatabase.get_events(get_invisible=False)
    return render_template('event/map.html', events=events)


@blueprint.route("/<string:event>/", methods=['get'])
def show_event(event: str):
    ev = MongoDatabase.select_event(event)
    if not ev:
        return "", 404

    ev_doc = ev.to_document()

    ev_name = ev_doc['name']
    ev_timestamp = ev_doc['timestamp']
    ev_latitude = ev_doc['latitude']
    ev_longitude = ev_doc['longitude']
    ev_alert_code = ev_doc['alert_code']
    ev_description = ev_doc['description']
    ev_tag = ev_doc['tag']

    return render_template('event/event.html', ev=ev, name=ev_name, timestamp=ev_timestamp, lat=ev_latitude,
                           long=ev_longitude, al_code=ev_alert_code, desc=ev_description, tag=ev_tag)


@blueprint.route("/image/<string:event>/", methods=['get'])
def get_event_image(event: str):
    ev = MongoDatabase.select_event(event)
    if not ev or not ev.has_image():
        return "", 404

    return MongoDatabase.send_photo(ev.get_image_name())

event-reporter/app/blueprints/report.py
from flask import Blueprint, redirect, render_template, url_for, request, flash
from werkzeug.datastructures import CombinedMultiDict

from app.extensions import MongoDatabase, EvrMail
from app.models import AlertCode, Event
from app.forms import ReportForm
from app.config import Config

blueprint = Blueprint("report", __name__, url_prefix='/report')


@blueprint.route("/", methods=['get'])
def report_event():
    form = ReportForm()
    return render_template('event/report.html', form=form)


@blueprint.route("/", methods=['post'])
def report_event_post():
    form = ReportForm(CombinedMultiDict((request.files, request.form)))

    if form.validate():
        image_extension = form.image.data.filename.split('.')[-1] if form.image.data else None

        ev = Event(
            timestamp=str(form.timestamp.data),
            latitude=form.latitude.data,
            longitude=form.longitude.data,
            alert_code=AlertCode.from_name(form.type.data),
            description=form.description.data,
            image_extension=image_extension
        )

        MongoDatabase.insert_event(ev)
        if ev.has_image():
            MongoDatabase.insert_photo(ev.get_image_name(), form.image.data)

        msg = EvrMail.create_new_event_message(Config.ADMIN_EMAILS, ev)
        EvrMail.send_message(msg)

        flash('Event reported')
        return redirect(url_for('event.show_events'))
    return render_template('event/report.html', form=form)

event-reporter/app/templates/drawer.html
<div class="mdl-layout__drawer">
    <span class="mdl-layout-title">
        Welcome
        <span class="mdl-badge" data-badge="{{ current_user.id[0] }}">{{ current_user.id }}</span>
    </span>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="{{ url_for('event.show_events') }}">Show events</a>
        <a class="mdl-navigation__link" href="{{ url_for('report.report_event') }}">Report event</a>
        {% if current_user.is_admin() %}
            <a class="mdl-navigation__link" href="{{ url_for('admin.event_approve_get') }}">Approve Events</a>
        {% endif %}
        <a class="mdl-navigation__link" href="/logout/">Logout</a>
    </nav>
</div>

event-reporter/app/templates/footer.html
<footer class="mdl-mini-footer" style="background: rgba(0, 0, 0, 0);">
    <div class="mdl-mini-footer__left-section">
        <div class="mdl-logo">
            <span class="android-title mdl-layout-title">
                <a href="{% if current_user.is_authenticated %}{{ url_for('user.home') }}
                         {% else %}/{% endif %}">
                    <img class="android-logo-image" src="/static/images/sdob.png"></a>
            </span>
        </div>
        <ul class="mdl-mini-footer__link-list">
            <li><a href="{{ url_for('no_auth.about') }}">About</a></li>
        </ul>
    </div>
    <div class="mdl-mini-footer__right-section">Copyright 2018 &copy; SDOB IP Bank</div>
</footer>

event-reporter/app/templates/layout.html
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License fo`r the specific language governing permissions and
  limitations under the License
-->
<html>
<head>
    <meta charset="utf-8">
    <title>{% block page_title %}
        Event Reporter
    {% endblock %}
    </title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Page styles -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-orange.min.css"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin=""/>

    <!-- Scripts -->
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
            integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
            crossorigin=""></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.js"></script>

    {% assets "css_all" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    {% block css %}{% endblock %}
    <style>
        #view-source {
            position: fixed;
            display: block;
            right: 0;
            bottom: 0;
            margin-right: 40px;
            margin-bottom: 40px;
            z-index: 900;
        }

        body {
            background: linear-gradient(-45deg, #ffffff, #bfbfbd, #ffffff, #bfbfbd);
            background-size: 400% 400%;
            animation: gradient 15s ease infinite;
        }

        @keyframes gradient {
            0% {
                background-position: 0% 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }

    </style>

</head>
<body id="gradient" class="{% block body_class %}sdob-body{% endblock %}">

{% block body %}
    <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-header">
        {% include "nav.html" %}
        {% include "drawer.html" %}

        <div class="mdl-layout__content">
            {% block outer_content %}
                <div class="mdl-grid demo-content">
                    <div class="mdl-layout-spacer"></div>
                    <div class="mdl-cell mdl-cell--6-col">
                        {% block content %}{% endblock %}
                    </div>
                    <div class="mdl-layout-spacer"></div>
                </div>
            {% endblock %}
        </div>

    </div>

    {% set errors = get_flashed_messages(category_filter=['error']) %}
    <div class="mdl-js-snackbar mdl-snackbar">
        <div class="mdl-snackbar__text {% if errors %}sdob-error-text{% endif %}" style="white-space: pre-line"></div>
        <button class="mdl-snackbar__action" type="button"></button>
    </div>

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    {% assets "js_all" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% block js %}{% endblock %}

    {% if errors %}
        {% set messages = '\\n'.join(errors) %}
    {% else %}
        {% set messages = '\\n'.join(get_flashed_messages()) %}
    {% endif %}
    {% if messages %}
        <script type="text/javascript">
            show_snackbar("{{ messages|safe }}");
        </script>
    {% endif %}
    <!-- end scripts -->
{% endblock %}

</body>
</html>

event-reporter/app/templates/nav.html
<header class="demo-header mdl-layout__header">
    <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">Event Reporter</span>
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable"></div>
    </div>
</header>