event-reporter/app/blueprints/event.py
from flask import Blueprint, render_template

from app.extensions import MongoDatabase

blueprint = Blueprint("event", __name__, url_prefix='/event')


@blueprint.route("/", methods=['get'])
def show_events():
    events = MongoDatabase.get_events(get_invisible=False)
    return render_template('event/map.html', events=events)


@blueprint.route("/<string:event>/", methods=['get'])
def show_event(event: str):
    ev = MongoDatabase.select_event(event)
    if not ev:
        return "", 404

    ev_doc = ev.to_document()

    ev_name = ev_doc['name']
    ev_timestamp = ev_doc['timestamp']
    ev_latitude = ev_doc['latitude']
    ev_longitude = ev_doc['longitude']
    ev_alert_code = ev_doc['alert_code']
    ev_description = ev_doc['description']
    ev_tag = ev_doc['tag']

    return render_template('event/event.html', ev=ev, name=ev_name, timestamp=ev_timestamp, lat=ev_latitude,
                           long=ev_longitude, al_code=ev_alert_code, desc=ev_description, tag=ev_tag)


@blueprint.route("/image/<string:event>/", methods=['get'])
def get_event_image(event: str):
    ev = MongoDatabase.select_event(event)
    if not ev or not ev.has_image():
        return "", 404

    return MongoDatabase.send_photo(ev.get_image_name())

event-reporter/app/blueprints/report.py
from flask import Blueprint, redirect, render_template, url_for, request, flash
from werkzeug.datastructures import CombinedMultiDict

from app.extensions import MongoDatabase, EvrMail
from app.models import AlertCode, Event
from app.forms import ReportForm
from app.config import Config

blueprint = Blueprint("report", __name__, url_prefix='/report')


@blueprint.route("/", methods=['get'])
def report_event():
    form = ReportForm()
    return render_template('event/report.html', form=form)


@blueprint.route("/", methods=['post'])
def report_event_post():
    form = ReportForm(CombinedMultiDict((request.files, request.form)))

    if form.validate():
        image_extension = form.image.data.filename.split('.')[-1] if form.image.data else None

        ev = Event(
            timestamp=str(form.timestamp.data),
            latitude=form.latitude.data,
            longitude=form.longitude.data,
            alert_code=AlertCode.from_name(form.type.data),
            description=form.description.data,
            image_extension=image_extension
        )

        MongoDatabase.insert_event(ev)
        if ev.has_image():
            MongoDatabase.insert_photo(ev.get_image_name(), form.image.data)

        msg = EvrMail.create_new_event_message(Config.ADMIN_EMAILS, ev)
        EvrMail.send_message(msg)

        flash('Event reported')
        return redirect(url_for('event.show_events'))
    return render_template('event/report.html', form=form)

event-reporter/app/templates/event/event.html
{% extends "layout.html" %}
{% block outer_content %}
<div class="mdl-grid">
<div class="mdl-cell mdl-cell--4-col"></div>
<div class="mdl-cell mdl-cell--4-col">
    <ul class="demo-list-item mdl-list">
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <p><strong>{{ ev.get_name_formatted() }}</strong></p>
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <p><strong>Timestamp</strong>  {{ ev.timestamp }}</p>
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <p><strong>Latitude</strong> {{ ev.latitude }}</p>
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <p><strong>Longitude</strong> {{ ev.longitude }}</p>
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <p><strong>Alert code</strong> {{ ev.alert_code.name }}</p>
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <p><strong>Description</strong></p>
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                {{ ev.description }}
            </span>
        </li>
    </ul>

    <img alt="No Image" src="{{ url_for('event.get_event_image', event=ev.name) }}"/>
</div>
<div class="mdl-cell mdl-cell--4-col"></div>
</div>
{% endblock %}

event-reporter/app/templates/event/map.html
{% extends "layout.html" %}
{% block outer_content %}
<center><div id="map" style="height: 720px; width: 1280px; vertical-align: middle;"></div></center>

{% for i in range(events|length): %}
<label id="points{{i}}"
       ts="{{events[i].timestamp}}"
       lat="{{events[i].latitude}}"
       lon="{{events[i].longitude}}"
       alert="{{events[i].alert_code.name}}"
       description="{{events[i].description}}"
       url="{{ url_for('event.show_event', event=events[i].name) }}"
       style="display: none;"></label>
{% endfor %}

<script>
    var roLat = 46.2;
    var roLong = 25.5;
    var defaultZoom = 7;

    // initialize map
    map = L.map('map', {minZoom: 7}).setView([roLat, roLong], defaultZoom);
    // set map tiles source
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
        maxZoom: 18,
    }).addTo(map);

    for (var i = 0; i < {{ events|length }}; ++i) {
        var ts = document.getElementById("points" + i).getAttribute('ts');
        var lat = document.getElementById("points" + i).getAttribute('lat');
        var long = document.getElementById("points" + i).getAttribute('lon');
        var alert = document.getElementById("points" + i).getAttribute('alert');
        var desc = document.getElementById("points" + i).getAttribute('description');
        var url = document.getElementById("points" + i).getAttribute('url');

        msg = alert + " at coordinates (" + lat + ", " + long  + ")<br/>"
        msg += "Date: " + ts + "<br/>"
        msg += desc + "<br/>"
        msg += "<a href=\"" + url + "\"> Show event </a>"

        marker = L.marker([lat, long]).addTo(map).on('click', onClick);
        // add popup to the marker
        marker.bindPopup(msg).openPopup();
    }

    function onClick(marker) {
        //alert(this.getLatLng());
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB90liH1hq_Eo7TvWH2ajg-R34tKSZdyWs&callback=initMap"></script>
{% endblock %}

event-reporter/app/templates/event/report.html
{% extends "layout.html" %}
{% from "macros/render_form.html" import render_field, render_field_2lines, render_checkbox %}
{% block outer_content %}
<div class="mdl-grid">
<div class="mdl-cell mdl-cell--4-col"></div>
<div class="mdl-cell mdl-cell--4-col">
    <h1><strong>REPORT</strong></h1>
    <br/>
    <form id="reportForm" class="form form-register" method="POST" enctype="multipart/form-data" action="" role="form">
    {{ form.hidden_tag() }}
    <ul class="demo-list-item mdl-list">
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                {{ render_field(form.timestamp) }}
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                {{ render_field(form.latitude) }}
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
               {{ render_field(form.longitude) }}
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                {{ render_field(form.type) }}
            </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                {{ render_field(form.description, field_args={'class': "form-control mdl-textfield__input", 'rows': 1}) }}
            </span>
        </li>
        <li class="mdl-list__item--two-line">
            <span class="mdl-list__item-primary-content">
                {{ form.image.label() }}
            </span>
            <span class="mdl-list__item-secondary-content">
                {{ form.image() }}
            </span>
        </li>
    </ul>
    <p><button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" type="submit"> Submit </button></p>
    </form>
</div>
<div class="mdl-cell mdl-cell--4-col"></div>
</div>
{% endblock %}